DROP TABLE IF EXISTS samples;
CREATE TABLE samples
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR
);

CREATE TABLE COMPANY
(
    company_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR,
    nation VARCHAR,
    location VARCHAR
);

CREATE TABLE MEMBER
(
    member_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR
);

CREATE TABLE notice
(
    notice_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    position VARCHAR,
    reward int,
    skill VARCHAR,
    content VARCHAR,
    company_id BIGINT,
    foreign key(company_id) references company (company_id)
);